### ISSUE TITLE
push_files regression

### ISSUE THREAD

**Issue by ai** [Arkweid/lefthook#100]
Lefhook: 0.7, 0.6.7, 0.6.3.

Config:

```yml
pre-push:
  parallel: true
  commands:
    lint:
      glob: "*.md"
      run: remark --no-stdout --frail --quiet {push_files}
```

I have 1 unpushed commit with `README.md` changes.

```
➜ n lefthook run pre-push -v
Lefthook v0.7.0
RUNNING HOOKS GROUP: pre-push

Files before filters: 
 []
Files after filters: 
 []
Files after escaping: 
 []

 lint (SKIP. NO FILES FOR INSPECTING)

SUMMARY: (SKIP EMPTY)
```
