### ISSUE TITLE
Question: regexp list in glob & exclude 

### ISSUE THREAD

**Issue by SnO2WMaN** [Arkweid/lefthook#152]
I cannot read Go, so I don't know the implementation of this tool.

Using regexp **list** in "glob" and "exclude" properties (like below one) is expected behavior? In my env, it seemed to be worked.

```yml
pre-commit:
  parallel: true
  commands:
    prettier:
      files: git diff --name-only --staged
      glob:
        - '*.{json,md}'
        - '*.{yml,yaml}'
      exclude:
        - README.md
        - CHANGELOG.md
      run: prettier --check {staged_files}
```

If so, I think writing on the readme will be good information for other user.
