### ISSUE TITLE
wiki: Comparison page

### ISSUE THREAD

**Issue by docwhat** [Arkweid/lefthook#25]
For this page: <https://github.com/Arkweid/lefthook/wiki/Comprasion-with-other-solutions>

The title:

```diff
- Comprasion with other solutions
+ Comparison with other solutions
```

Another utility to compare with: [pre-commit](https://pre-commit.com)

It has nice docs, but the syntax is a bit arcane.  You can share hooks easily, though.  It lacks a curated catalog of shared hooks, alas.

**Comment by Arkweid** [comment]
FIxed.

https://pre-commit.com/ refused connection and repository haven't any docs. So I can't inspect features :(

**Comment by docwhat** [comment]
Weird. The site works for me from the USA. 

The code repo is https://github.com/pre-commit/pre-commit/

The docs are hosted on github via https://github.com/pre-commit/pre-commit.github.io

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Arkweid** [comment]
I researched the problem. The Russian authorities block the IP address on which the resource is located... three times.
https://gyazo.com/5bb75ab0c51e2a48d3b0e1343cfd50a5

pre-commit.github.io redirect me on https://pre-commit.com/ :(

I looked through the docs. The tool looks quite complicated.

**Comment by Arkweid** [comment]
@docwhat OK, I've got comparison results. I tested it on discourse CI example.
pre-commit version is 1.15.2

`pre-commit`:
- Require python runtime.
- Verbose config.
- Not very clear documentation.
- **Very slow(3x)**. I've got 25sec execution time in average vs 7,5 secs for lefthook. Dunno know why it so slow. Parallel mode enabled by default.
- **Breaks original output from commands**

## pre-commit config:
```yml
-   repo: local
    hooks:
    -   id: rubocop
        always_run: true
        name: rubocop
        files: git ls-files --cached
        entry: bundle exec rubocop --parallel
        language: system
    -   id: prettier
        always_run: true
        name: prettier
        files: git ls-files --cached
        entry: yarn prettier --list-different app/assets/stylesheets/**/*.scss app/assets/javascripts/**/*.es6 test/javascripts/**/*.es6
        language: system
    -   id: eslint-assets
        always_run: true
        name: eslint-assets
        files: git ls-files --cached
        entry: yarn eslint --ext .es6 app/assets/javascripts
        language: system
    -   id: eslint-test
        always_run: true
        name: eslint-test
        files: git ls-files --cached
        entry: yarn eslint --ext .es6 test/javascripts
        language: system
    -   id: eslint-plugins-assets
        always_run: true
        name: eslint-plugins-assets
        files: git ls-files --cached
        entry: yarn eslint --ext .es6 plugins/**/assets/javascripts
        language: system
    -   id: eslint-plugins-test
        always_run: true
        name: eslint-plugins-test
        files: git ls-files --cached
        entry: yarn eslint --ext .es6 plugins/**/test/javascripts
        language: system
    -   id:  eslint-assets-tests
        always_run: true
        name:  eslint-assets-tests
        files: git ls-files --cached
        entry: yarn eslint app/assets/javascripts test/javascripts
        language: system
```
![pre-commit output](https://cdn1.savepice.ru/uploads/2019/7/11/a2c75c12045e4d13256bed151fe34292-full.png)

## Lefthook config:
```
lints:
  parallel: true
  commands:
    rubocop:
      run: bundle exec rubocop --parallel
    prettier:
      run: yarn prettier --list-different app/assets/stylesheets/**/*.scss app/assets/javascripts/**/*.es6 test/javascripts/**/*.es6
    eslint-assets:
      run: yarn eslint --ext .es6 app/assets/javascripts
    eslint-test:
      run: yarn eslint --ext .es6 test/javascripts
    eslint-plugins-assets:
      run: yarn eslint --ext .es6 plugins/**/assets/javascripts
    eslint-plugins-test:
      run: yarn eslint --ext .es6 plugins/**/test/javascripts
    eslint-assets-tests:
      run: yarn eslint app/assets/javascripts test/javascripts
```
![lefthook output](https://cdn1.savepice.ru/uploads/2019/7/11/0348899d1e0b54cf787fd9a61704f80e-full.png)
