### ISSUE TITLE
Error: index out of range

### ISSUE THREAD

**Issue by dlinch** [Arkweid/lefthook#28]
Hi there, I stumbled upon this project from a cool EvilMartians blog [post](https://dev.to/evilmartians/lefthook-crystalball-and-git-magic-for-smooth-development-experience-33mc).

I went to implement in my own project, and I tried both the homebrew binary and the Node module, and when I run `lefthook install` or `yarn lefthook install` I get the same error:
`runtime error: index out of range`

All I have done at this point is create the `lefthook.yml` file and download the binary, so I'm petty sure I'm not doing anything wrong.

**Comment by Arkweid** [comment]
Hello @dlinch. Thank you for issue.
Lets figure out what is going on. The message looks like internal golang error.
Tell me your version.
```
lefthook version
```
Then give me example of `lefthook.yml` file
Also try to delete all files from `.git/hooks` directory and run `lefthook install` again.

**Comment by dlinch** [comment]
Lefthook version: 0.6.0

lefthook.yml:
```
pre-push:
  parallel: true
  commands:
    rubocop:
      tags: backend
      run: if [[ `git status --porcelain |egrep '^A|^M' |egrep '\\.ts'` ]]; then yarn lint; fi && git status --porcelain |egrep '^A|^M' |grep '.rb' |awk '{print $2}' |xargs bundle exec rubocop
    rspec:
      tags: rspec backend
      run: bundle exec crystalball --fail-fast
```


So removing everything from .git/hooks seemed to do the trick. I did have an implementation with Husky that I was porting over into lefthook. Is there a reason why having content inside the hooks would make lefthook fail? It seems like it should be able to handle that. Probably by overwriting the hooks defined in `lefthook.yml`
