### ISSUE TITLE
Docker Usage - The Input Device is no TTY

### ISSUE THREAD

**Issue by enthusiasmus** [Arkweid/lefthook#32]
Dear lefthook team,

lefthook.yml

```
pre-push:
  parallel: true
  scripts:
    "rubocop":
      runner: docker exec -it <container-name> {cmd}
```

.lefthook/pre-push
```
#!/bin/bash

rubocop
```

on push 

> /home/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/lefthook-0.6.3/libexec/lefthook-linux run pre-push origin git@gitlab.com:repo/repo.git
> Lefthook v0.6.3
> RUNNING HOOKS GROUP: pre-push
> 
>   EXECUTE > rubocop
> the input device is not a TTY
> 
> SUMMARY: (done in 0.03 seconds)
> 🥊  rubocop
> error: Fehler beim Versenden einiger Referenzen nach 'git@gitlab.com:repo/repo.git

any ideas how to fix this?

thanks in advance!
lukas

p.s.: docs (https://github.com/Arkweid/lefthook/blob/master/docs/full_guide.md) `docker exec -it --rm <container_id_or_name> {cmd}` the `--rm` option shouldn't be there

**Comment by enthusiasmus** [comment]
this produces the same error :/
```
pre-push:
  parallel: true
  commands:
    rubocop:
      runner: docker-compose exec <container> bundle exec pronto run -r rubocop
```

**Comment by Arkweid** [comment]
@enthusiasmus unfortunately I could not reproduce the problem.
Try the simplest variant as possible:
```
pre-push:
  commands:
    rubocop:
      runner: docker exec <container> bundle exec rubocop
```
Is it works?
