### ISSUE TITLE
{incoming_files} shortcut on post-merge hook

### ISSUE THREAD

**Issue by dlinch** [Arkweid/lefthook#44]
Is there an API for incoming file changes from the `post-merge` hook?
I have my hook setup to run `db:migrate` after a merge. If I could have a check to see if any of the incoming files were migration files then I could skip the command altogether if none of the files match a regex filter of some kind to check if they're migrations.

maybe something like this?
```yml
post-merge:
  commands:
  glob: "db/migrate/*"
  migrate: {incoming_files} && bundle exec rails db:migrate
```
