### ISSUE TITLE
RuboCop config being ignored?

### ISSUE THREAD

**Issue by andyw8** [Arkweid/lefthook#45]
My RuboCop is configured to ignore schema changes:

```yml
require: 'rubocop-rails'
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/schema.rb' # auto-generated
```
When I run RuboCop directly, there are no issues.

I have Lefthook configured with:

`run: bundle exec rubocop {staged_files} --parallel`

When it's triggered through Lefthook, it seems to ignore the config.

I tried changing it to explicitly specify the config file, but it made no difference:

`run: bundle exec rubocop --config .rubocop.yml {staged_files} --parallel`
