### ISSUE TITLE
`parallel: true` is unsafe

### ISSUE THREAD

**Issue by asottile** [Arkweid/lefthook#59]
In any situation where fixers are involved, `parallel: true` is unsafe

Here's a minimal example:

```dockerfile
FROM ubuntu:bionic
RUN : \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        git \
        python3-pip \
        python3-setuptools \
    && apt-get clean
RUN : \
    && curl --location --silent --output /tmp/lefthook.gz https://github.com/Arkweid/lefthook/releases/download/v0.6.3/lefthook_0.6.3_Linux_x86_64.gz \
    && echo '0876ae7a862cb26aa5bd50173502dfd836cd16317f7af18be0797deeb3e1cfcd  /tmp/lefthook.gz' | sha256sum --check \
    && gunzip /tmp/lefthook.gz \
    && mv /tmp/lefthook /usr/local/bin \
    && chmod +x /usr/local/bin/lefthook \
    && which lefthook

RUN pip3 install pyupgrade
        
WORKDIR /src

COPY lefthook.yml ./

ENV \
    GIT_AUTHOR_EMAIL=a@example.com \
    GIT_AUTHOR_NAME='A A' \
    GIT_COMMITTER_EMAIL=a@example.com \
    GIT_COMMITTER_NAME='A A'

RUN : \
    && git init . \
    && echo "world = 1; print('hello {}'.format(world))  # trailing ws " > t.py \
    && seq 1 1000 | xargs --replace cp t.py t{}.py \
    && lefthook install \
    && git add .

CMD ["bash", "-c", "git commit -m test >& /dev/null; sha256sum *.py | cut -d' ' -f1 | sort | uniq -c"]
```

```yaml
pre-commit:
  parallel: true
  commands:
    pyupgrade:
      # tac is used to make this more reproducible, it happens without it
      # just more rarely
      files: git diff --staged --name-only -- '*.py' | tac
      run: pyupgrade --py36-plus {files}
    trailing-whitespace:
      files: git diff --staged --name-only -- '*.py'
      run: sed -i 's/ *$//g' {files}
```

```bash
docker build -t test .
docker run --rm -ti test
```

```console
$ docker run --rm -ti test
      1 d8a9bda5f09334903e4ba7bb0e3dc766106ccf379d71ce4eb3eba46b6274fd8f
   1000 f6fadaa8047971e6253655ecee3a2ffcb5645983e913daa0f6110de6deea1d43
```

All files should have the same sha256sum as they were identical inputs (and therefore should have identical outputs)
