### ISSUE TITLE
Pass arguments to custom script?

### ISSUE THREAD

**Issue by asmaloney** [Arkweid/lefthook#67]
Given the example:
```yaml
commit-msg:
  scripts:
    "template_checker":
      runner: bash
```

How would I pass `{staged_files}` to the `template_checker` script?

(If this is possible, I suggest adding it to the docs.)

Thanks!
