### ISSUE TITLE
Support for relative roots/monorepos

### ISSUE THREAD

**Issue by ffloyd** [Arkweid/lefthook#72]
For example, when you working with monorepo you may want to have config like this:

```yaml
pre-commit:
  commands:
    elixir_format:
      root: "/backend"
      glob: "*.{ex,exs}"
      run: mix format --check-formatted {staged_files}
    ts_format:
      root: "/frontend"
      glob: "*.{ts,tsx}"
      run: npm run format_check {staged_files}
```

Possible `root` option behaviour:

* helpers like `{staged_files}` should return paths relative to provided root path
* option `files` should use root path as working dir
* option `run` should use root path as working dir
