### ISSUE TITLE
Problems with RUBY_PLATFORM 'x64-mingw32'

### ISSUE THREAD

**Issue by swiehr** [Arkweid/lefthook#79]
`bin/lefthook` (don't see it in `.rubygems` of this repo though) of the installed gem states:
```
  when /windows/
    'lefthook-win.exe'
  else
```

Unfortunately in my environment `RUBY_PLATFORM` is `x64-mingw32` and I got:
```
$ lefthook install
C:/Tools/rubyinstaller-2.4.4-2-x64/lib/ruby/gems/2.4.0/gems/lefthook-0.6.3/bin/lefthook:11:in `<top (required)>': Invalid platform. (RuntimeError)
        from C:/Tools/rubyinstaller-2.4.4-2-x64/bin/lefthook:23:in `load'
        from C:/Tools/rubyinstaller-2.4.4-2-x64/bin/lefthook:23:in `<main>'
```
This can be solved: If I add the value to the `when` I can install the hook.

When testing in my git-bash I get the color sequences as text, e.g.:
```
$ lefthook run pre-push
C:/Tools/rubyinstaller-2.4.4-2-x64/lib/ruby/gems/2.4.0/gems/lefthook-0.6.3/libexec/lefthook-win.exe run pre-push
←[36mRUNNING HOOKS GROUP:←[0m ←[1mpre-push←[0m
←[36m
  EXECUTE >←[0m ←[1mrubocop←[0m
←[33m(SKIP. NO FILES FOR INSPECTING)←[0m
←[36m
  EXECUTE >←[0m ←[1mtest←[0m
```

Not sure what's the root cause for that as for example I have a nicely colored prompt in that same bash.

**Comment by Arkweid** [comment]
I am not experienced with windows platform, as I know the color sequences for terminals can be different.
You can change the terminal or disable colors with this option in config:
```
# colors: false
```

**Comment by swiehr** [comment]
> I am not experienced with windows platform, as I know the color sequences for terminals can be different.
> You can change the terminal or disable colors with this option in config:
> 
> ```
> colors: false
> ```

At which level do I have to put that? 

My `lefthook.yml` looks like this:
```
pre-push:
  parallel: true
  commands:
    test:
      run: bundle exec rspec
    rubocop:
      files: git diff --name-only HEAD master
      glob: "*.{rb}"
      run: bundle exec rubocop
```
I tried before `pre-push` at top-level and right below `pre_push` without effect.
The cmdline option `--no-colors` doesn't seem to work for the Windows binary.

**Comment by Arkweid** [comment]
Try this:
```
colors: false

pre-push:
  parallel: true
  commands:
    test:
      run: bundle exec rspec
    rubocop:
      files: git diff --name-only HEAD master
      glob: "*.{rb}"
      run: bundle exec rubocop
```
https://github.com/Arkweid/lefthook/blob/master/docs/full_guide.md#disable-colors
