### ISSUE TITLE
Only run on changed files, but not use those files

### ISSUE THREAD

**Issue by erikaxel** [Arkweid/lefthook#8]
Hi,

I have a task (i18n-tasks for Rails) that needs to run whenever I update the yml files. 
I expect to be able to write
```
pre-push:
  commands:
    i18n-linting:
      files: git diff --name-only HEAD master # only changes
      glob: "*.yml"
      run: i18n-tasks check-normalized
```
However, when I do this, it always runs, even when there are no changes to the yml files (as according to git). Btw, I'm fine with the command running whenever there are changes to yml files not related to the task, that is not the issue here.

I get the correct behaviour if i add {files} to the run command:
```
run: i18n-tasks check-normalized {files}
```
The problem is that i18n-tasks does not take files as an argument. So I must remove {files} from the run command.

So my expected behaviour would be to not run it if files return 0 files even when not used in the run command.

**Comment by Arkweid** [comment]
Thanks for your note @erikaxel! I going to add this behavior asap.

**Comment by Arkweid** [comment]
@erikaxel added in v0.3.2

**Comment by erikaxel** [comment]
Thanks, seems to work perfectly!

**Comment by BasixKOR** [comment]
Hi, I think this issue still occurs when `files` are not provided. My use-case is like this:

```yml
    typescript:
      glob: "*.{js,ts,jsx,tsx}"
      run: yarn tsc --noEmit
```

This runs even if no files are changed.
