### ISSUE TITLE
glob not finding files in pre-push hook

### ISSUE THREAD

**Issue by tconroy** [Arkweid/lefthook#83]
Hello, I'm having trouble getting this pre-push hook to detect files, specifically for the `style` command:

```
pre-push:
  parallel: true
  commands:
    javascript:
      files: git diff --name-only HEAD @{push}
      glob: "*.{ts,tsx,js,jsx}"
      run: npx eslint -- {files}
    styles:
      files: git diff --name-only HEAD @{push}
      glob: "*.{less,css}"
      run: npx stylelint -- {files}
    types:
      run: npm run type-check
```

When I manually run `git diff --name-only HEAD @{push}`, I see an expected `.less` file in the output. However, when I run `./node_modules/.bin/lefthook -v run styles`, I see this output:

```
Lefthook v0.6.3
RUNNING HOOKS GROUP: styles

SUMMARY: (SKIP EMPTY)
```

Any idea why this may be? It seems like the glob is failing somehow. This is not a new file but rather modifying an existing file in the repo.
